-- =============================================================================
-- V5__seed_default_tenant.sql
-- Inserts the `demo` tenant used by local development and integration tests.
--
-- ⚠️  DEVELOPMENT-ORIENTED SEED.
-- Idempotent: safe to re-run. Does NOT execute on production-like databases
-- (guarded by current_database()).
--
-- Downstream migrations (V6+) reference this row by its slug:
--     SELECT id FROM edushift.tenants WHERE slug = 'demo'
-- so the actual UUID is generated here on first run and stays stable thereafter.
-- =============================================================================

DO $$
DECLARE
    v_tenant_id     uuid;
    v_now           timestamptz := NOW() AT TIME ZONE 'UTC';
    v_target_slug   text        := 'demo';
BEGIN
    -- Skip seed on databases that look like production. Adjust the list if your
    -- production database name differs.
    IF current_database() IN ('edushift_prod', 'edushift_production') THEN
        RAISE NOTICE 'V5 seed skipped on production database %', current_database();
        RETURN;
    END IF;

    -- Idempotency: bail if the tenant already exists (any non-deleted row).
    SELECT id INTO v_tenant_id
    FROM edushift.tenants
    WHERE lower(slug) = v_target_slug AND deleted = false;

    IF v_tenant_id IS NOT NULL THEN
        RAISE NOTICE 'V5 seed: tenant "%" already exists (id=%)', v_target_slug, v_tenant_id;
        RETURN;
    END IF;

    -- Generate a UUIDv4 for the PK (UUIDv7 is generated by the application
    -- runtime; for SQL seeds gen_random_uuid is the practical choice).
    v_tenant_id := gen_random_uuid();

    INSERT INTO edushift.tenants (
        id,
        public_uuid,
        created_at,
        updated_at,
        deleted,
        name,
        slug,
        status,
        settings
    ) VALUES (
        v_tenant_id,
        gen_random_uuid(),
        v_now,
        v_now,
        false,
        'EduShift Demo',
        v_target_slug,
        'ACTIVE',
        jsonb_build_object(
            'locale',     'es-PE',
            'timezone',   'America/Lima',
            'currency',   'PEN',
            'isDevSeed',  true
        )
    );

    RAISE NOTICE 'V5 seed: created tenant "%" with id=%', v_target_slug, v_tenant_id;
END;
$$;
