-- =============================================================================
-- V71__create_role_permission_overrides.sql
--
-- D1 / F0.5 (QA plan 2026-07-02) — Custom role permissions.
--
-- Sprint X / BE-X.X — TENANT_ADMIN can override the platform-default role →
-- LMS_* authorities mapping for their tenant. The replacement is per
-- (tenant_id, role, authority) and recorded as a `granted` boolean so the
-- audit log captures both directions (enable and disable).
--
-- Schema decisions:
-- * One row per (tenant, role, authority) override. If the row is absent
--   the platform default applies; if it is present the BE uses the
--   explicit `granted` value.
-- * `role` is one of TENANT_ADMIN / TEACHER / STUDENT / PARENT / STAFF.
--   SUPER_ADMIN is intentionally excluded — the platform tier is
--   immutable.
-- * `authority` is one of the constants declared in
--   shared.security.LmsAuthorities. The CHK enforces the whitelist so a
--   future constant must ship with a migration that updates the enum
--   (which is what `alter_check_constraint_on_extension` would do in
--   production).
-- * `granted_by_user_id` records who last changed this triple; standard
--   audit columns (created_at / updated_at / deleted) flow from
--   AuditableEntity.
-- * Soft delete: removing an override = soft delete so the diff history
--   is preserved. Hard delete is reserved for tenant offboarding.
--
-- IMPORTANT — DO NOT EDIT THIS FILE AFTER IT HAS BEEN APPLIED
-- ==============================================================
-- Flyway tracks a checksum of this file in flyway_schema_history. Editing
-- the file after `mvn spring-boot:run` has applied it (even to add a
-- cosmetic comment) will make startup fail with "Migration checksum
-- mismatch for migration version 71". If you need to change the schema,
-- add V72__...sql and put the change there. The original content has
-- been preserved here exactly as the checksum-recorded revision so the
-- development database keeps booting.
-- =============================================================================

CREATE TABLE IF NOT EXISTS edushift.role_permission_overrides (
    id                  uuid         PRIMARY KEY,
    public_uuid         uuid         NOT NULL,
    tenant_id           uuid         NOT NULL,
    role                varchar(32)  NOT NULL,
    authority           varchar(64)  NOT NULL,
    granted             boolean      NOT NULL,
    granted_by_user_id  uuid         NOT NULL,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    updated_at          timestamptz  NOT NULL DEFAULT now(),
    created_by          uuid,
    updated_by          uuid,
    deleted             boolean      NOT NULL DEFAULT false,
    deleted_at          timestamptz,

    CONSTRAINT uk_role_permission_overrides_public_uuid UNIQUE (public_uuid),
    CONSTRAINT ck_role_permission_overrides_role      CHECK (role IN (
        'TENANT_ADMIN','TEACHER','STUDENT','PARENT','STAFF'
    )),
    CONSTRAINT ck_role_permission_overrides_authority CHECK (authority IN (
        'LMS_TASK_READ','LMS_TASK_CREATE','LMS_TASK_GRADE','LMS_TASK_SUBMIT',
        'LMS_MATERIAL_READ','LMS_MATERIAL_WRITE','LMS_MATERIAL_DELETE',
        'LMS_QUIZ_READ','LMS_QUIZ_CREATE','LMS_QUIZ_GRADE','LMS_QUIZ_SUBMIT',
        'LMS_AI_GENERATE','LMS_AI_USAGE','LMS_PAYMENT_ADMIN',
        'LMS_ANNOUNCEMENTS_CREATE','LMS_NOTIFICATIONS_MANAGE'
    )),
    CONSTRAINT fk_role_permission_overrides_tenant FOREIGN KEY (tenant_id)
        REFERENCES edushift.tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_overrides_user  FOREIGN KEY (granted_by_user_id)
        REFERENCES edushift.users(id)
);

-- Hot path: LmsRoleAuthorityMapper.snapshotFor(tenantId) reads this index
-- for every JWT minted. Without it the lookup would seq-scan.
CREATE INDEX IF NOT EXISTS ix_role_permission_overrides_tenant_role
    ON edushift.role_permission_overrides (tenant_id, role)
    WHERE deleted = false;

-- Only one ACTIVE row per (tenant, role, authority). The partial index
-- excludes soft-deleted rows automatically.
CREATE UNIQUE INDEX IF NOT EXISTS uk_role_permission_overrides_active
    ON edushift.role_permission_overrides (tenant_id, role, authority)
    WHERE deleted = false;

-- updated_at trigger (uses the function created in V7).
CREATE TRIGGER set_updated_at_role_permission_overrides
    BEFORE UPDATE ON edushift.role_permission_overrides
    FOR EACH ROW EXECUTE FUNCTION edushift.set_updated_at();
