-- =============================================================================
-- V73__create_help_progress_and_feedback.sql
--
-- Help manuals — interactive progress + feedback (Sprint Help / BE-18.x).
--
-- The help system (BE-15.1 + BE-18.x) exposes per-role user manuals at
-- `docs/manuales/<rol>/<file>.md`. The autoevaluación chapters contain
-- `- [ ]` checklists. To make them interactive we persist two things:
--
--   1. `help_progress` — one row per (user, role, chapter file, item id)
--      capturing whether the user has marked the item as done. The item
--      id is a deterministic SHA-256 hash (truncated) of the markdown
--      line text, computed by the FE; we never need to migrate IDs even
--      when the manual text is edited, because the BE treats unknown
--      IDs as orphans on next read.
--
--   2. `help_feedback` — append-only comments left by users against a
--      chapter (or against the manual as a whole). Used by the platform
--      team to triage gaps in coverage.
--
-- Both tables extend AuditableEntity (created_at / updated_at /
-- created_by / updated_by / deleted). Tenant isolation is enforced by
-- the `tenant_id` column + tenant interceptor; we never accept it from
-- the request body.
--
-- IMPORTANT — DO NOT EDIT THIS FILE AFTER IT HAS BEEN APPLIED.
-- =============================================================================

CREATE TABLE IF NOT EXISTS edushift.help_progress (
    id           uuid         PRIMARY KEY,
    public_uuid  uuid         NOT NULL,
    tenant_id    uuid         NOT NULL,
    user_id      uuid         NOT NULL,
    role         varchar(32)  NOT NULL,
    chapter_file varchar(64)  NOT NULL,
    item_id      varchar(64)  NOT NULL,
    checked      boolean      NOT NULL,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    created_by   uuid,
    updated_by   uuid,
    deleted      boolean      NOT NULL DEFAULT false,
    deleted_at   timestamptz,

    CONSTRAINT uk_help_progress_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_help_progress_tenant FOREIGN KEY (tenant_id)
        REFERENCES edushift.tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_help_progress_user FOREIGN KEY (user_id)
        REFERENCES edushift.users(id) ON DELETE CASCADE,
    CONSTRAINT ck_help_progress_role CHECK (role IN (
        'SUPER_ADMIN','TENANT_ADMIN','TEACHER','STUDENT','PARENT','STAFF'
    ))
);

-- Hot path: the FE pulls the whole checklist state for a chapter with a
-- single query. Partial unique index keeps soft-deleted rows out.
CREATE UNIQUE INDEX IF NOT EXISTS uk_help_progress_active
    ON edushift.help_progress (user_id, role, chapter_file, item_id)
    WHERE deleted = false;

-- List-by-user dashboard query.
CREATE INDEX IF NOT EXISTS ix_help_progress_user_role
    ON edushift.help_progress (user_id, role)
    WHERE deleted = false;

CREATE TABLE IF NOT EXISTS edushift.help_feedback (
    id            uuid         PRIMARY KEY,
    public_uuid   uuid         NOT NULL,
    tenant_id     uuid         NOT NULL,
    user_id       uuid         NOT NULL,
    role          varchar(32)  NOT NULL,
    chapter_file  varchar(64),                              -- nullable = general manual feedback
    body          text         NOT NULL,
    status        varchar(16)  NOT NULL DEFAULT 'OPEN',     -- OPEN | ACKNOWLEDGED | RESOLVED
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    created_by    uuid,
    updated_by    uuid,
    deleted       boolean      NOT NULL DEFAULT false,
    deleted_at    timestamptz,

    CONSTRAINT uk_help_feedback_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_help_feedback_tenant FOREIGN KEY (tenant_id)
        REFERENCES edushift.tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_help_feedback_user FOREIGN KEY (user_id)
        REFERENCES edushift.users(id) ON DELETE CASCADE,
    CONSTRAINT ck_help_feedback_role CHECK (role IN (
        'SUPER_ADMIN','TENANT_ADMIN','TEACHER','STUDENT','PARENT','STAFF'
    )),
    CONSTRAINT ck_help_feedback_status CHECK (status IN (
        'OPEN','ACKNOWLEDGED','RESOLVED'
    ))
);

CREATE INDEX IF NOT EXISTS ix_help_feedback_user_role
    ON edushift.help_feedback (user_id, role, created_at DESC)
    WHERE deleted = false;

CREATE INDEX IF NOT EXISTS ix_help_feedback_status
    ON edushift.help_feedback (status, created_at DESC)
    WHERE deleted = false;

COMMENT ON TABLE edushift.help_progress IS
    'Per-user checklist state for the autoevaluación chapters of each role manual.';
COMMENT ON TABLE edushift.help_feedback IS
    'User-submitted feedback on manuals/chapters; reviewed by the platform team.';